spring.application.name=my-api

spring.datasource.url=jdbc:mysql://localhost:3306/teste_api_maven?useTimezone=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=9320
spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
